luts = [
    "AsQLhBq3xodjpZfpqoY4hZb5YmEM9HzoE9FjUnv7z2Qw",
    "J1Kf3N9cVso1UcnGqWkr1KYAFDgoNMugaTBTR7oz9Xmq",
    "Abcr5mDFpCZPXLDDPP2cpyWqKLXpCrXhxC1BZ4ju8TXD",
    "BNzHhJyuNmnq5ytRVKD9jYAGBzNauZhdjPoAQaKQT1hm",
    "FmyM3xvVzM4WiSnN75XM4RRG1BhQa9C5MEkMyAfc2dp",
    "A5gjMgtEE8fzNB2AaSyZKPBtz4CbiDm7QQQe6aMWuXSb",
    "5JSzZB1bnVqZebb1DuvYU2TBHKSMDM8mUcE4JJGWWn3Z",
    "FSGBpXZGjw21kq3jDtonUccrvYRyGtJFZNX3sUtHFEq3",
    "Dhq8Ay7z9ao1VgMgQk5AD8qU9YwVvt1euBE3xhh5pKm9",
    "4935Rb5XsaYkjuSWGuKNLBn4taBF7JuFufRCuefvbXG8",
]
